### ISSUE TITLE
Error when applying custom dataset

### ISSUE THREAD

**Issue by pickleL** [josedolz/LiviaNET#4]
Hi, your work is fantastic! I want to apply it on the MICCAI dataset but got this error:

============== EPOCH: 1/5 =================
 --- SubEPOCH: 1/2
 ... Get samples for subEpoch...
 ... getting 200 samples per subject...
...Processing subject: 1. 20.0 % of the whole training set...
...Processing subject: 2. 40.0 % of the whole training set...
...Processing subject: 3. 60.0 % of the whole training set...
...Processing subject: 4. 80.0 % of the whole training set...
...Processing subject: 5. 100.0 % of the whole training set...
Traceback (most recent call last):
  File "./networkTraining.py", line 82, in <module>
    networkTraining(sys.argv[1:])
  File "./networkTraining.py", line 77, in networkTraining
    startTraining(networkModelName,configIniName)
  File "/Users/elaine/Desktop/LiviaNET-master/src/LiviaNet/startTraining.py", line 147, in startTraining
    myLiviaNet3D.trainingData_y.set_value(gt_samplesAll, borrow=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/sharedvalue.py", line 146, in set_value
    self.container.value = new_value
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/link.py", line 479, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/type.py", line 150, in filter
    converted_data = theano._asarray(data, self.dtype)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/misc/safe_asarray.py", line 34, in _asarray
    rval = np.asarray(a, dtype=dtype, order=order)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/numeric.py", line 474, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: ('could not broadcast input array from shape (19,19,19) into shape (19,19)', 'Container name "None"')

The files are in Nifti. Thanks in advance!

**Comment by josedolz** [comment]
Hi, from this ("from shape (19,19,19) into shape (19,19)") it seems to me that you are trying to convert from 3D image shapes to 2D, and that causes the error. I am not with my computer (actually just left for holidays), if you still have the problem when I am back, in round 3 weeks, I can check it with you. Sorry for that.

Jose

**Comment by pickleL** [comment]
Hi, thanks very much for the quick response! 
Yeah that's what I'm wondering. Shouldn't the network take 3D inputs instead of 2D? 
Sorry if this is not a quick question for you I can wait. I just really hope to apply the model on MICCAI. Thanks!

**Comment by josedolz** [comment]
Hi, sorry for my late reply, I am currently on holidays. Inputs of the network are 3D not 2D.If you can wait couple of weeks that I am back I can look into your setting.

Best

**Comment by josedolz** [comment]
Hi @pickleL 

Please have a look to this other user that found the same problem than you:

https://github.com/josedolz/LiviaNET/issues/5

It seems that for him, images and their corresponding ground truths did not match. Maybe you can double check this, :).

Best
